### PR TITLE
fix(#64): call forCall() on announcement thread, not SDP-negotiation thread

### LINKED ISSUE #64: bug: WrongThreadException — confined arena created on forCall() thread, announcement runs on different codecExecutor thread
## Problem

`NativeRtpCodec.forCall()` calls `Arena.ofConfined()` — confining the arena to the thread that calls `forCall()`.
That call happens inside `SdpNegotiator.selectCodec()`, which is invoked on whatever `codecExecutor` platform thread runs `processAcceptedInvite → acceptAndAnnounce → negotiateAndRespond`.

Immediately after, `acceptAndAnnounce` submits a **second** task to the same `ManagedExecutorService`:

```java
Future<?> callFuture = this.managedExecutorService.submit(() -> {
    Thread.sleep(1_000);
    this.announcementLoop.play(session, player, factory, sessionId, media);
});
```

Because `codecExecutor` is a **pool** of platform threads, this second task can (and frequently does) land on a **different** platform thread.
`announcementLoop.play()` → `encode()` accesses `this.stateSegment` (confined arena), and the `finally` block calls `close()` on that arena — both from the wrong thread → `WrongThreadException`.

### Why it appears intermittently

When the same thread happens to pick up the inner task (e.g. thread A finishes the outer sleep and negotiation and immediately picks up the inner task before other tasks arrive), there is no exception and the call works.
When a different thread picks up the inner task, the call fails with `WrongThreadException`.

### Evidence from trace log

```
Thread 00000940 — negotiateAndRespond (forCall() creates arena)
Thread 000008da — AnnouncementLoop.play() → WrongThreadException on encode/close

Thread 000009af — negotiateAndRespond + play() (SAME thread → call works)
```

```
W Error closing codec after call
java.lang.WrongThreadException: Attempted to close a confined arena from outside the confinement thread
```

## Root cause

Two `managedExecutorService.submit/execute` calls are used.
`forCall()` is called in the **first** task; `encode()` and `close()` run in the **second** task.

## Fix

Move `forCall()` from `SdpNegotiator.selectCodec()` into the announcement lambda (the second executor task), so the arena is created, used for encoding, and closed all on the **same** platform thread.

`SdpNegotiator.negotiate()` should return the descriptor codec (factory bean, no arena) wrapped in `NegotiatedRtpCodec` with the negotiated PT.
The announcement lambda calls `media.codec().forCall()` (on its own thread) to obtain the per-call codec before encoding begins.
Add a `forCall()` override to `NegotiatedRtpCodec` that returns `new NegotiatedRtpCodec(delegate.forCall(), negotiatedPayloadType)` so the negotiated PT is preserved.

### Files to change

- `codecs/sip/.../NegotiatedRtpCodec.java` — add `forCall()` override
- `war/.../SdpNegotiator.java` — `selectCodec()` returns descriptor codec, **not** `descriptor.forCall()`
- `war/.../CallAcceptor.java` — call `media.codec().forCall()` at the start of the announcement lambda; close the per-call codec in `finally`

### PR DESCRIPTION
**Pull request by bmarwell**
## Problem

`Arena.ofConfined()` creates a thread-confined arena.
`SdpNegotiator.selectCodec()` was calling `forCall()` (and thus creating the arena) on the SDP-negotiation thread (thread B).
The announcement lambda was submitted to `managedExecutorService` and ran on a different thread (thread C).
Any call to `encode()` or `close()` from thread C on the arena owned by thread B threw `WrongThreadException`, causing Android callers to hear nothing.

## Fix

- `SdpNegotiator.selectCodec()` now stores the **CDI bean descriptor** in `NegotiatedRtpCodec` without calling `forCall()`.
- `CallAcceptor.acceptAndAnnounce()` and `acceptAndPlayMenu()` call `forCall()` at the **start of the announcement/menu lambda**, on the same executor thread that will also call `encode()` and `close()`.
- `RtpAudioPlayer` gains an explicit `RtpCodec` constructor parameter; the old `(CallMedia, PcmDecoderFactory)` constructor is deprecated and delegates.
- `NegotiatedRtpCodec` Javadoc updated to describe both lifecycle roles (descriptor before `forCall()`, per-call instance after).
- `SdpNegotiatorTest` asserts `forCall()` is **never** called during codec selection.

Closes #64

### CODE REVIEW

File: war/src/main/java/de/bmarwell/proximo/pitido/war/media/RtpAudioPlayer.java [hunk 1]
```diff
@@ -68,21 +68,38 @@ public class RtpAudioPlayer implements AudioPlayer {
...
+     * @param pcmDecoderFactory the factory used to select the decoder for each audio resource
+     * @deprecated Use {@link #RtpAudioPlayer(CallMedia, RtpCodec, PcmDecoderFactory)} instead.
+     *             Passing the codec explicitly ensures the confined arena is created on the
+     *             thread that will encode and close it, preventing {@link WrongThreadException}.
+     */
+    @Deprecated
+    public RtpAudioPlayer(CallMedia callMedia, PcmDecoderFactory pcmDecoderFactory) {
+        this(callMedia, callMedia.codec(), pcmDecoderFactory);
+    }
+
```
Comment (bmarwell) [inline war/src/main/java/de/bmarwell/proximo/pitido/war/media/RtpAudioPlayer.java]: No usages, remove
