### PR TITLE
fix(core): auto-discover public IP via JAX-RS client

### LINKED ISSUE #24: feat: auto-detect public IP via ident.me when SIP_REGISTRATION_ENABLED=true and SIP_PUBLIC_HOST is absent
## Problem

When `SIP_REGISTRATION_ENABLED=true` and `SIP_PUBLIC_HOST` is not set, `LocalSipHostProvider` currently falls back to a local IP for the Contact header.
Behind NAT (home router, Docker host), this produces a Contact that is unreachable from the registrar, causing registration to succeed but incoming calls to fail (the registrar can't route back to the app).

## Proposed solution

When `SIP_REGISTRATION_ENABLED=true` **and** `SIP_PUBLIC_HOST` is not configured, query a public-IP discovery service automatically:

```
https://ident.me          # plain text, IPv4 or IPv6
https://api4.my-ip.io/v2/json  # JSON, IPv4 only, good fallback
https://api.ipify.org     # plain text, IPv4 only
```

Try them in order; use the first successful response.
Cache the result for an hour.
Log the discovered IP at INFO level so it is visible in the startup log and later.

When `SIP_REGISTRATION_ENABLED=false` (softphone / dev mode), skip the lookup entirely — no public IP is needed.

## Notes

- `LocalSipHostProvider` in `core` is the right place for this logic.
- The HTTP call must time out quickly (≤ 2 s) to avoid blocking startup.
- Do not fail startup if all services are unreachable — fall back to the local IP and log a WARNING.

### PR DESCRIPTION
**Pull request by bmarwell**
Closes #24

## What

Adds `PublicIpDiscoveryService` — an `@ApplicationScoped` CDI bean that queries plain-text IP-echo services to determine the public IP for the SIP `Contact` header, using the JAX-RS 2.1 `Client` API.

## Why JAX-RS (not `java.net.http`)

A container application should use container-managed resources.
Liberty's `jaxrsClient` feature provides a managed `ClientBuilder` SPI at runtime.

## The JAXB compile-time issue (and fix)

`javax.ws.rs-api:2.1.1` declares `requires transitive java.xml.bind` in its `module-info.class`.
Java 17+ removed `java.xml.bind` from the JDK, so javac cannot resolve it from the JDK module path alone.

Fix: add `javax.xml.bind:jaxb-api:2.3.1` as `provided` scope — it puts the `java.xml.bind` module on the compile-time module path.
At runtime, Liberty's `jaxb` feature (added to `server.xml`) provides it.

## Liberty features added (versionless — pinned by `javaee-8.0` platform)

- `jaxrsClient` — JAX-RS 2.1 client API + managed `ClientBuilder`
- `jaxb` — Java XML Bindings; satisfies the runtime `java.xml.bind` requirement

## Resolution order in `LocalSipHostProvider.get()`

1. `SIP_PUBLIC_HOST` / `sip.public.host` — explicit operator override, no network call
2. `PublicIpDiscoveryService.discover()` — when `sip.registration.enabled=true` (default)
3. First non-loopback IPv4 from local network interfaces — fallback with WARNING log

## Details

- Services tried in order: `ident.me`, `api.ipify.org`, `checkip.amazonaws.com`
- 2-second connect + read timeout per request
- 1-hour in-memory cache (`AtomicReference` + `volatile Instant`)
- Response validated via `InetAddress.getByName()` before use
- 7 unit tests: first-wins, fallback, all-fail, invalid body, caching, trailing newline, no-extra-calls

### CODE REVIEW

File: core/src/main/java/de/bmarwell/proximo/pitido/core/sip/PublicIpDiscoveryService.java [hunk 1]
```diff
@@ -0,0 +1,153 @@
...
+                .readTimeout(REQUEST_TIMEOUT_SECONDS, TimeUnit.SECONDS)
+                .build();
+    }
+
+    @PreDestroy
+    void close() {
+        if (this.client != null) {
+            this.client.close();
+        }
+    }
```
Comment (bmarwell) [inline core/src/main/java/de/bmarwell/proximo/pitido/core/sip/PublicIpDiscoveryService.java]: Client is open for too long. One client per discovery should suffice.

File: core/src/main/java/de/bmarwell/proximo/pitido/core/sip/PublicIpDiscoveryService.java [hunk 2]
```diff
@@ -0,0 +1,153 @@
...
+ *
+ * <h2>Services queried (in order)</h2>
+ *
+ * <ol>
+ *   <li>{@code https://ident.me} — plain text, IPv4 or IPv6</li>
+ *   <li>{@code https://api.ipify.org} — plain text, IPv4 only</li>
+ *   <li>{@code https://checkip.amazonaws.com} — plain text, IPv4 only</li>
+ * </ol>
+ */
+@ApplicationScoped
```
Comment (bmarwell) [inline core/src/main/java/de/bmarwell/proximo/pitido/core/sip/PublicIpDiscoveryService.java:54]: This does not need to be long-lived

File: core/src/main/java/de/bmarwell/proximo/pitido/core/sip/PublicIpDiscoveryService.java [hunk 3]
```diff
@@ -0,0 +1,153 @@
...
+public class PublicIpDiscoveryService {
+
+    private static final System.Logger LOGGER = System.getLogger(PublicIpDiscoveryService.class.getName());
+
+    static final List<String> DISCOVERY_URLS =
+            List.of("https://ident.me", "https://api.ipify.org", "https://checkip.amazonaws.com");
```
Comment (bmarwell) [inline core/src/main/java/de/bmarwell/proximo/pitido/core/sip/PublicIpDiscoveryService.java]: Wrap in `URI.create()`, this should be tested at compile time / test time.

Comment (bmarwell) [reply core/src/main/java/de/bmarwell/proximo/pitido/core/sip/PublicIpDiscoveryService.java]: Static is okay for now, can make it configurable later if we need to.

File: core/src/main/java/de/bmarwell/proximo/pitido/core/sip/PublicIpDiscoveryService.java [hunk 4]
```diff
@@ -0,0 +1,153 @@
...
+        return Optional.empty();
+    }
+
+    private Optional<String> queryService(String url) {
+        try {
+            String body = this.client
+                    .target(url)
+                    .request(MediaType.TEXT_PLAIN_TYPE)
+                    .get(String.class)
+                    .strip();
```
Comment (bmarwell) [inline core/src/main/java/de/bmarwell/proximo/pitido/core/sip/PublicIpDiscoveryService.java]: Do all services work with `TEXT_PLAIN`? Maybe one service class per service URI would be better for best control of media type and response body parsing, but I think this is okay for now.

File: core/pom.xml [hunk 5]
```diff
@@ -38,6 +38,27 @@
...
+      <artifactId>jaxb-api</artifactId>
+      <scope>provided</scope>
+    </dependency>
+
+    <!-- Apache CXF: JAX-RS client implementation for tests -->
+    <dependency>
+      <groupId>org.apache.cxf</groupId>
+      <artifactId>cxf-rt-rs-client</artifactId>
+      <scope>test</scope>
+    </dependency>
```
[the remark this answers is not in the document]
Comment (bmarwell) [reply core/pom.xml:61]: This is wrong, CXF is loaded via serviceprovider

File: pom.xml [hunk 6]
```diff
@@ -80,6 +80,35 @@
...
+      </dependency>
+
+      <!-- Apache CXF JAX-RS client — test-time ClientBuilder SPI implementation -->
+      <dependency>
+        <groupId>org.apache.cxf</groupId>
+        <artifactId>cxf-rt-rs-client</artifactId>
+        <version>3.6.5</version>
+        <scope>test</scope>
+      </dependency>
+
```
[the remark this answers is not in the document]
Comment (bmarwell) [reply pom.xml:111]: This is wrong, CXF is loaded via serviceprovider
